- platform: gree
  # required settings:
  name: climatiseur Robin
  host: <192.168.1.32>
  mac: '<94:24:B8:A3:9A:09>'
  # optional settings:
  port: 7000
  timeout: 10
  target_temp_step: 1
  temp_sensor: <temperature sensor in first AC room>
  lights: <input_boolean used to switch lights on/off of your first AC>
  xfan: <input_boolean used to switch xfan on/off of your first AC>
  health: <input_boolean used to switch the Health option on/off of your first AC>
  sleep: <input_boolean used to switch sleep on/off of your first AC>
  powersave: <input_boolean used to switch powersave on/off of your first AC>
  eightdegheat: <input_boolean used to switch 8 degree heating on/off on your first AC>

- platform: gree
  # required settings:
  name: climatiseur Raphaël
  host: <192.168.1.135>
  mac: '<94:24:B8:A3:6F:F1>'
  # optional settings:
  port: 7000
  timeout: 10
  target_temp_step: 1
